### PR TITLE
Fixed Czech translation

### PR DESCRIPTION
**Pull request by janherman**
## Describe the PR

Added Czech translation to the translations array in index.php, because the translation was not applied. Also changed one word in translation file itself.

### CODE REVIEW

**Comment by afbora** [comment]
Base language as EN is updated. May be you want add missing lines with compare:

https://github.com/getkirby/editor/blob/master/i18n/en.php

**Comment by janherman** [comment]
Oh, sorry for that. I absolutely missed the updated lines. :man_facepalming: I will add them. Can I ask you how to do it properly? Is it possible to update this pull request, or do I have to create another one? Unfortunately I am not very experienced in these processes. Thanks!

**Comment by afbora** [comment]
@janherman You push new commits to own branch as https://github.com/janherman/editor/tree/czech-translation 👍

**Comment by afbora** [comment]
@janherman Awesome, done!

**Comment by janherman** [comment]
@afbora Thanks for your help!

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
