### PR TITLE
Fixed comparing kirby version

### PR DESCRIPTION
**Pull request by afbora**
## Related issue

https://forum.getkirby.com/t/kirby-editor-throws-kirby-version-error-but-version-is-correct/16502

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [ ] Passing all unit tests
- [ ] Fixed code style issues with CS fixer and `composer fix`
- [ ] Added in-code documentation (if needed)

### CODE REVIEW

**Comment by distantnative** [comment]
If you now check for higher than 3.3.0, the error message should say as well.

But are you sure 3.3.1 is required and not 3.3.0?

**Comment by afbora** [comment]
@distantnative `Kirby version 3.3.0 or higher`??

**Comment by afbora** [comment]
@distantnative Hmm, also composer.json file says `^3.2` 🤔 

````json
"require-dev": {
    "getkirby/cms": "^3.2"
}
````

**Comment by lukasbestle** [comment]
This bug was already fixed by @bastianallgeier in 04bb7131db996ef18d2eb9c3ee065daa0044c814 (Editor 1.0.1). Probably @plagasul used Editor 1.0.0 for testing.

Regarding the `require-dev` setting in `composer.json`: The dev requirements don't have an effect when the plugin is installed, only when the `composer install` is run inside the plugin's folder for development. I'd assume that Bastian set that version constraint when 3.3.0 wasn't out. In the end it doesn't matter. :)

**Comment by afbora** [comment]
@lukasbestle so editor plugin require min Kirby v3.3.1, right?

**Comment by lukasbestle** [comment]
No, 3.3.0.

**Comment by afbora** [comment]
@lukasbestle so it's should be like my PR? Exception will throw on equal values now.

So throw an exception only `3.3.0 > KIRBY` mean `KIRBY < 3.3.0`. Am I wrong?

**Comment by afbora** [comment]
> This bug was already fixed by @bastianallgeier in [04bb713]

@lukasbestle Unfortunately this issue was corrected missing. Lets compare if Kirby version is `3.3.0`

````php
if (version_compare('3.3.0', '3.3.0', '>=')) {
    throw new Exception('The editor requires Kirby version 3.3.0 or higher');
}
````
Exception will throw because of values are equal. 
It must be at least 3.3.1 to pass the condition here.

If the minimum version supports 3.3.0, I insist that the comparison is incorrect 😄 

I think the condition should be written in order to understand it more clearly:

````php
if (version_compare($this->kirby()->version(), '3.3.0', '<')) {
    throw new Exception('The editor requires Kirby version 3.3.0 or higher');
}
````

**Comment by lukasbestle** [comment]
Ah, I see it now. The comparison was the wrong way round. Thanks for spotting that!

It should be:

```php
version_compare($this->kirby()->version(), '3.3.0', '>=') !== true
```

Or your changed variant, which is exactly the same. :)

**Review by lukasbestle — APPROVED** [review]

**Pull request merged**
